[project]
name = "skies"
revision = "1.0"

[profiles.default]


[profiles.development]
CACHIX_AUTH_TOKEN = { description = "A personal token grants complete access to the HTTP API, including any binary caches you have access to.", required = false, default = "" }
